---
- name: "Install requirements"
  ansible.builtin.package:
    name: "{{ sssd_pkg }}"
    state: present

- name: "Configuring sssd"
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: "0600"
  become: true
  when:
    - sssd_conf_domains is defined
    - sssd_conf_domains | length > 0
  notify: restart sssd

- name: Import tasks for debian
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family == 'Debian'

- name: Import tasks for redhat7
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family | lower }}7.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Import tasks for redhat >= 8
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version >= '8'

- name: "Enable and start sssd"
  ansible.builtin.service:
    name: sssd
    enabled: true
    state: started
  when:
    - sssd_svc_start is defined
    - sssd_svc_start|bool
