---
- name: Stop sssd service
  ansible.builtin.systemd:
    name: sssd
    state: stopped
    enabled: false
  failed_when: false

- name: Remove SSSD data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/sss/db
    - /var/lib/sss/mc
    - /var/lib/sss/pipes
    - /var/lib/sss/pubconf
    - /var/log/sssd

- name: Purge SSSD packages on Debian/Ubuntu
  ansible.builtin.apt:
    name: "sssd*"
    state: absent
    purge: "yes"
    autoremove: "yes"
    update_cache: "yes"
  when: ansible_os_family == "Debian"

- name: Remove SSSD packages on RedHat family
  ansible.builtin.dnf:
    name: "sssd*"
    state: absent
    autoremove: "yes"
  when: ansible_os_family == "RedHat"
