---
- name: "DEBIAN | Disable sssd sub sockets"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
  with_items:
    - sssd-ssh.socket
    - sssd-sudo.socket
    - sssd-nss.socket
    - sssd-pam.socket
    - sssd-pam-priv.socket
    - sssd-pac.socket
    - sssd-autofs.socket
  when:
    - ansible_distribution_release == "bullseye"
    - sssd_disable_svc_socket is defined
    - sssd_disable_svc_socket|bool

- name: "DEBIAN | Configuring nsswitch"
  ansible.builtin.template:
    src: nsswitch.conf.j2
    dest: "/etc/nsswitch.conf"
    owner: root
    group: root
    mode: "0644"
  become: true
  when:
    - sssd_nssswitch_config is defined
    - sssd_nssswitch_config | length > 0
  notify: restart sssd

- name: "DEBIAN | Create homedir automatically"
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/common-session"
    regexp: "^session required        pam_mkhomedir.so"
    insertbefore: '^session [default=1]'
    line: "session required        pam_mkhomedir.so skel=/etc/skel/ umask={{ sssd_umask }}"
    state: present
  when:
    - sssd_create_homedir is defined
    - sssd_create_homedir|bool
  notify: restart sssd

- name: "DEBIAN | Change default umask"
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/common-session"
    regexp: "^session    optional     pam_umask.so umask=077"
    insertbefore: '^session optional            pam_sss.so'
    line: "session    optional     pam_umask.so umask={{ sssd_umask }}"
    state: present
  when:
    - sssd_change_umask is defined
    - sssd_change_umask | bool
  notify: restart sssd
