---
- name: "Disable sssd sub sockets"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
  with_items:
    - sssd-ssh.socket
    - sssd-sudo.socket
    - sssd-nss.socket
    - sssd-pam.socket
    - sssd-pam-priv.socket
    - sssd-pac.socket
    - sssd-autofs.socket
  when: ansible_distribution_release == "bullseye"

- name: "DEBIAN | Configuring nsswitch"
  ansible.builtin.template:
    src: nsswitch.conf.j2
    dest: "/etc/nsswitch.conf"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: restart sssd

- name: "DEBIAN | Create homedir automatically"
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/common-session"
    regexp: "^session required        pam_mkhomedir.so"
    insertafter: '^session optional            pam_sss.so'
    line: "session required        pam_mkhomedir.so skel=/etc/skel/ umask=0022"
    state: present
