---
- name: "restart sssd"
  ansible.builtin.service:
    name: sssd
    state: restarted

- name: "restart oddjobd"
  ansible.builtin.service:
    name: oddjobd

- name: "authselect apply-changes"
  ansible.builtin.command: "authselect apply-changes"

- name: "reload oddjob service"
  ansible.builtin.systemd:
    name: "oddjobd"
    state: restarted
    daemon_reload: true
  become: true
